### ISSUE TITLE
Difference between this project and maxmind/geoipupdate?

### ISSUE THREAD

**Issue by r7l** [crazy-max/geoip-updater#104]
Been using the one from [Maxmind](https://github.com/maxmind/geoipupdate) so far and just found out about this project. I am kind curious what the difference is between this project and the one from Maxmind?

**Comment by crazy-max** [comment]
When geoip-updater was created, the one from Maxmind did not have a Docker image. It also lacks of a  proper native cron implementation and has to rely on a [dirty while loop in its entrypoint](https://github.com/maxmind/geoipupdate/blob/28230b7aeec3eb7fb62870197509ff6e937646f7/docker/entry.sh#L63-L74).
