### ISSUE TITLE
Error missing flags: --license-key=0123456789

### ISSUE THREAD

**Issue by the-lazy-fox** [crazy-max/geoip-updater#87]
#### Steps to reproduce this issue

I have this container running for few months now but for few days now, I have this error showing up:
geoip-updater: error: missing flags: --license-key=0123456789

#### Expected behaviour

> The container should run like it was before (I guess)

#### Actual behaviour

> The container is crashing

### Logs

```
geoip-updater: error: missing flags: --license-key=0123456789
```

Thanks :)

**Comment by crazy-max** [comment]
@the-lazy-fox Hard to tell without the command you use to run geoip-updater and/or the configuration. Please create a proper [bug report](https://github.com/crazy-max/geoip-updater/issues/new?assignees=&labels=&template=bug_report.md).
